INSERT INTO category(ID, DESCRIPTION) VALUES (1001, 'Comic Book');
INSERT INTO category(ID, DESCRIPTION) VALUES (1002, 'Movies');
INSERT INTO category(ID, DESCRIPTION) VALUES (1003, 'Books');

INSERT INTO supplier(ID, NAME) VALUES (1001, 'Panini Comics');
INSERT INTO supplier(ID, NAME) VALUES (1002, 'Amazon');

INSERT INTO PRODUCT(ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE, CREATE_AT) VALUES (1, 'crises na infinitas terras', 1001, 1002, 10, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE, CREATE_AT) VALUES (2, 'Guerra Civil', 1001, 1001, 5, CURRENT_TIMESTAMP);
INSERT INTO PRODUCT(ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE, CREATE_AT) VALUES (3, 'Os vingadores', 1002, 1002, 2, CURRENT_TIMESTAMP);